### ISSUE TITLE
Upgrade to node20

### ISSUE THREAD

**Issue by dscho** [git-for-windows/get-azure-pipelines-artifact#684]
We need to do this "by spring 2024", see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by rimrul** [comment]
We probably also need to bump the version on git-for-windows/setup-git-for-windows-sdk, as we get deprecation warnings about that action despite main already using node20

**Comment by dscho** [comment]
I'll take care of updating this Action.
